name: Copilot Code Review

on:
  pull_request:
    # brand-new PRs, drafts marked “Ready for review”, and PRs that were closed then reopened
    types: [opened, ready_for_review, reopened]

permissions:
  pull-requests: write   # lets the extension add Copilot as a reviewer

jobs:
  ask-copilot:
    if: ${{ github.event.pull_request.draft == false }}   # skip still-draft PRs
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # gh CLI picks this up automatically

    steps:
      - name: Install gh-copilot-review extension
        run: gh extension install ChrisCarini/gh-copilot-review

      - name: Ask Copilot to review this PR
        run: gh copilot-review "${{ github.event.pull_request.html_url }}"